### ISSUE TITLE
[Redis Broker] Replace Client Command 

### ISSUE THREAD

**Issue by coding-trees** [triggermesh/brokers#142]
As part of the redis broker the [Probe()](https://github.com/triggermesh/brokers/blob/main/pkg/backend/impl/redis/redis.go#L284-L295) method will make a `CLIENT` command to verify that a connection has been successfully established. 

Unfortunately, the `CLIENT` command (along with others) is blocked by GCP Memstore: https://cloud.google.com/memorystore/docs/redis/product-constraints#blocked_redis_commands

In the event that the `CLIENT` command fails can it try a different command, like `PING`, to perform the proof of a successful connection?

**Comment by odacremolbap** [comment]
By the looks of the [INFO command docs](https://redis.io/commands/info/), it seems to be categorized as _dangerous_.
It is possible that a Redis admin does not want to add that ACL for security reasons.

I am adding at [this PR](https://github.com/triggermesh/brokers/pull/144) a new flag that defaults to current behavior, but that can use [XINFO STREAM](https://redis.io/commands/xinfo-stream/) for probing, or just skip probing.

Would that solve this issue?

**Comment by odacremolbap** [comment]
Sorry @coding-trees , just saw your ping solution.
I think yours is ok. I'll cancel my PR.

Thanks!

**Comment by coding-trees** [comment]
> Sorry @coding-trees , just saw your ping solution. I think yours is ok. I'll cancel my PR.
> 
> Thanks!

No problem, should have mentioned in my original comment that I had something in mind and would attempt a solution :)
